"""
FertiliQ Example Query Runner
Executes the 10 canonical example queries end-to-end and saves formatted
responses to examples/query_responses.md.

Prerequisites:
  1. python generate_data.py
  2. python src/ingest.py
  3. GEMINI_API_KEY set in environment

Run: python run_examples.py
"""

import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT))

EXAMPLE_QUERIES = [
    "I have MTHFR C677T variant - how much folic acid should I take?",
    "What CoQ10 dosage is recommended for egg quality?",
    "How do I sync my biomarker data with the FertiliQ app?",
    "What does a low AMH level mean for my fertility?",
    "When is the best time to have sex to maximize conception chances?",
    "My vitamin D is 18 ng/mL, what should I do?",
    "What foods should I eat during the follicular phase?",
    "My partner has low sperm motility - what supplements help?",
    "Why does my genetic report say I have high oxidative stress risk?",
    "I've been trying for 8 months, what does FertiliQ recommend I check next?",
]

OUTPUT_PATH = ROOT / "examples" / "query_responses.md"


def run_pipeline(query: str, doc_col, forum_col, blog_col) -> dict:
    """Run the full RAG pipeline for one query.

    Args:
        query: User question string.
        doc_col, forum_col, blog_col: ChromaDB collections.

    Returns:
        Dict with response, latency_ms, contradictions_present, contradiction_confidence.
    """
    from src.retrieval import hybrid_search
    from src.reranking import (
        Chunk, deduplicate, detect_contradictions, embed_chunks, llm_rerank
    )
    from src.generation import generate_response, get_top3_source_metadata
    from src.logger import log_query

    t0 = time.time()

    raw = hybrid_search(query, doc_col, forum_col, blog_col, top_k_per_col=10)

    chunks = [
        Chunk(
            id=r["id"],
            content=r.get("metadata", {}).get("parent_content") or r["content"],
            metadata=r["metadata"],
            rrf_score=r.get("rrf_score", 0.0),
        )
        for r in raw
    ]

    embed_chunks(chunks)
    deduped = deduplicate(chunks, threshold=0.85)
    after_dedup = len(deduped)

    units, clean = detect_contradictions(deduped)
    contradiction_types = [u.contradiction_type for u in units]

    top3, _ = llm_rerank(units, clean, query)
    response, conf, contradictions_present = generate_response(query, top3)

    latency_ms = int((time.time() - t0) * 1000)

    log_query(
        query=query,
        candidates_retrieved=len(raw),
        after_dedup=after_dedup,
        contradictions_detected=contradictions_present,
        contradiction_types=contradiction_types,
        contradiction_confidence=conf if contradictions_present else 0.0,
        top3_sources=get_top3_source_metadata(top3),
        response_generated=True,
        latency_ms=latency_ms,
    )

    return {
        "response": response,
        "latency_ms": latency_ms,
        "contradictions_present": contradictions_present,
        "contradiction_confidence": conf,
        "contradiction_types": contradiction_types,
    }


def main() -> None:
    """Run all 10 example queries and write results to examples/query_responses.md."""
    from src.ingest import GeminiEmbeddingFunction, get_chroma_client, get_collections
    from src.gemini_client import get_client

    if not os.environ.get("GEMINI_API_KEY"):
        print("ERROR: GEMINI_API_KEY not set.")
        sys.exit(1)

    get_client()  # initialise singleton
    embed_fn = GeminiEmbeddingFunction()
    client = get_chroma_client()
    doc_col, forum_col, blog_col = get_collections(client, embed_fn)

    if doc_col.count() == 0:
        print("ERROR: ChromaDB is empty. Run generate_data.py then src/ingest.py first.")
        sys.exit(1)

    OUTPUT_PATH.parent.mkdir(exist_ok=True)
    lines = [
        "# FertiliQ RAG — Example Query Responses\n",
        "Auto-generated by `run_examples.py`\n",
        "---\n",
    ]

    for i, query in enumerate(EXAMPLE_QUERIES, 1):
        print(f"[{i:2d}/10] {query[:70]}...")
        result = run_pipeline(query, doc_col, forum_col, blog_col)
        contradiction_note = ""
        if result["contradictions_present"]:
            contradiction_note = (
                f" ⚠️ Contradiction detected ({', '.join(result['contradiction_types'])}) — "
                f"confidence: {result['contradiction_confidence']:.2f}"
            )

        lines.append(f"## Query {i}\n")
        lines.append(f"**Question:** {query}\n\n")
        lines.append(
            f"**Latency:** {result['latency_ms']} ms{contradiction_note}\n\n"
        )
        lines.append("**Response:**\n\n")
        lines.append(result["response"])
        lines.append("\n\n---\n\n")

        print(f"       Done in {result['latency_ms']} ms"
              + (" [CONTRADICTION]" if result["contradictions_present"] else ""))

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nAll responses saved to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
